services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: task4
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d task4"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3001
      CLIENT_URL: http://localhost:3001
      DATABASE_URL: postgresql://admin:admin123@db:5432/task4
      JWT_SECRET: admin123
    ports:
      - "3001:3001"

volumes:
  pg_data:
